package fatfractioncalc;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ariane
 */
public class Gui extends javax.swing.JFrame {
    // Bounds selected when the user starts running the program
    int[] bounds;
    String nigzFilePath;
    String niFolderPath;
    String dicomFolderPath;
    String csvFilePath;
    boolean singlePatient;
    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        BATMinSlider = new javax.swing.JSlider();
        BATMaxSider = new javax.swing.JSlider();
        TIMinSlider = new javax.swing.JSlider();
        WATMaxSlider = new javax.swing.JSlider();
        WATMinSlider = new javax.swing.JSlider();
        TIMaxSlider = new javax.swing.JSlider();
        allPatientBtn = new javax.swing.JButton();
        singlePatientBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        startBtn = new javax.swing.JButton();
        CSVPathBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel4formFocusGained(evt);
            }
        });

        BATMinSlider.setMajorTickSpacing(5);
        BATMinSlider.setMinorTickSpacing(5);
        BATMinSlider.setPaintLabels(true);
        BATMinSlider.setPaintTicks(true);
        BATMinSlider.setValue(20);
        BATMinSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BATMinSliderMouseClicked(evt);
            }
        });

        BATMaxSider.setMajorTickSpacing(5);
        BATMaxSider.setMinorTickSpacing(5);
        BATMaxSider.setPaintLabels(true);
        BATMaxSider.setPaintTicks(true);
        BATMaxSider.setValue(60);
        BATMaxSider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BATMaxSiderMouseClicked(evt);
            }
        });

        TIMinSlider.setMajorTickSpacing(5);
        TIMinSlider.setMinorTickSpacing(5);
        TIMinSlider.setPaintLabels(true);
        TIMinSlider.setPaintTicks(true);
        TIMinSlider.setValue(20);
        TIMinSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TIMinSliderMouseClicked(evt);
            }
        });

        WATMaxSlider.setMajorTickSpacing(5);
        WATMaxSlider.setMinorTickSpacing(5);
        WATMaxSlider.setPaintLabels(true);
        WATMaxSlider.setPaintTicks(true);
        WATMaxSlider.setValue(90);
        WATMaxSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WATMaxSliderMouseClicked(evt);
            }
        });

        WATMinSlider.setMajorTickSpacing(5);
        WATMinSlider.setMinorTickSpacing(5);
        WATMinSlider.setPaintLabels(true);
        WATMinSlider.setPaintTicks(true);
        WATMinSlider.setValue(80);
        WATMinSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        WATMinSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WATMinSliderMouseClicked(evt);
            }
        });

        TIMaxSlider.setMajorTickSpacing(5);
        TIMaxSlider.setMinorTickSpacing(5);
        TIMaxSlider.setPaintLabels(true);
        TIMaxSlider.setPaintTicks(true);
        TIMaxSlider.setValue(100);
        TIMaxSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TIMaxSliderMouseClicked(evt);
            }
        });

        allPatientBtn.setText("All Patients");
        allPatientBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allPatientBtnMouseClicked(evt);
            }
        });
        allPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allPatientBtnActionPerformed(evt);
            }
        });

        singlePatientBtn.setText("Single Patient");
        singlePatientBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                singlePatientBtnMouseClicked(evt);
            }
        });
        singlePatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singlePatientBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("BAT Min (%)");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("WAT Min (%)");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Total Interscapular and Auxilary Fat Max (%)");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setText("Total Interscapular and Auxilary Fat Min (%)");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setText("BAT Max (%)");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("WAT Max (%)");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel7.setText("Fat Fraction and Volume Calculation Program ");

        jTextField1.setText("GUSTO_6YR_");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("GUSTO_GUSTO_RESEARCH_20160403_, GUSTO_GUSTO_RESEARCH_2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setText("AX_VIBE_6ECHOES_SCAPULA_LL2_RR_FF_////, AX_VIBE_6ECHOES_SCAPULA_LL2_FF_////");
        jTextField3.setToolTipText("");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setText("/////////_BAT6.nii.gz");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel10.setText("Study directory contains:");

        jLabel11.setText("MRI image type template:");

        jLabel13.setText("Subject directoy template: ");

        jLabel15.setText("Segmentation file template:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(308, 308, 308))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(BATMinSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BATMaxSider, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(51, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(401, 401, 401))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(WATMinSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TIMinSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(103, 103, 103)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TIMaxSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WATMaxSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(33, 33, 33))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(singlePatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(allPatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BATMinSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BATMaxSider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WATMaxSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WATMinSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TIMinSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TIMaxSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(singlePatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allPatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel8.setText("Calculation Progress");

        startBtn.setText("Start");
        startBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startBtnMouseClicked(evt);
            }
        });
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        CSVPathBtn.setText("Select CSV Path");
        CSVPathBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSVPathBtnMouseClicked(evt);
            }
        });
        CSVPathBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSVPathBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CSVPathBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(10, 10, 10)))
                                .addGap(660, 660, 660))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(335, 335, 335))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CSVPathBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private boolean dicomFileChooser() {
            JFileChooser dicomFolderChooser = new JFileChooser();
            dicomFolderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int dicomFolderRetVal = dicomFolderChooser.showDialog(jLabel1, "Select MRI Directory");
            if (dicomFolderRetVal == JFileChooser.CANCEL_OPTION) {
                return false;
            }
            File dicomFile = dicomFolderChooser.getSelectedFile();
            if (dicomFile.isDirectory()) {
                dicomFolderPath = dicomFile.getAbsolutePath();
                return true;
            } else {
                JOptionPane.showMessageDialog(dicomFolderChooser, "You selected a file not a folder");
                return false;
            }
    }

    
    private void startBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startBtnMouseClicked
        if ((niFolderPath == null && nigzFilePath == null) || dicomFolderPath == null || csvFilePath == null) {
            return;
        }
        bounds = new int[6];
        bounds[0] = TIMinSlider.getValue();
        bounds[1] = TIMaxSlider.getValue();
        bounds[2] = WATMinSlider.getValue();
        bounds[3] = WATMaxSlider.getValue();
        bounds[4] = BATMinSlider.getValue();
        bounds[5] = BATMaxSider.getValue();
        start();
    }//GEN-LAST:event_startBtnMouseClicked

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed

    }//GEN-LAST:event_startBtnActionPerformed

    private void CSVPathBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSVPathBtnMouseClicked
        boolean returned = false;
        while (returned == false) {
            JFileChooser csvFileChooser = new JFileChooser();
            csvFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int csvFileRetVal = csvFileChooser.showOpenDialog(jLabel1);
            if (csvFileRetVal == JFileChooser.CANCEL_OPTION) {
                return;
            }
            File csvFile = csvFileChooser.getSelectedFile();            
            if (csvFile.isDirectory()) {
                String csvName = JOptionPane.showInputDialog("Input CSV File Name");
                csvFilePath = csvFile.getAbsolutePath() + "/" + csvName;
                System.err.println("" + csvFilePath);
                returned = true;
            } else {
                JOptionPane.showMessageDialog(csvFileChooser, "You selected a folder not a file");
            }
        }
    }//GEN-LAST:event_CSVPathBtnMouseClicked

    private void CSVPathBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSVPathBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CSVPathBtnActionPerformed

    private void jPanel4formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel4formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4formFocusGained

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void singlePatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singlePatientBtnActionPerformed

    }//GEN-LAST:event_singlePatientBtnActionPerformed

    private void singlePatientBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singlePatientBtnMouseClicked
        singlePatient = true;
        JFileChooser niFileChooser = new JFileChooser();
        boolean returned = false;
        while (returned == false) {
            int niFileRetVal = niFileChooser.showDialog(jLabel1, "Select single patient segment file");
            if (niFileRetVal == JFileChooser.CANCEL_OPTION) {
                return;
            }
            File niFile = niFileChooser.getSelectedFile();
            if (niFile.isFile()) {
                nigzFilePath = niFile.getAbsolutePath();
                returned = true;
            } else {
                JOptionPane.showMessageDialog(niFileChooser, "You selected a folder not a file");
            }
        }
        returned = false;
        while (returned == false) {
            returned = dicomFileChooser();
        }
    }//GEN-LAST:event_singlePatientBtnMouseClicked

    private void allPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allPatientBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allPatientBtnActionPerformed

    private void allPatientBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allPatientBtnMouseClicked
        singlePatient = false;
        boolean returned = false;
        while (returned == false) {
            JFileChooser niFolderChooser = new JFileChooser();
            niFolderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int niFolderRetVal = niFolderChooser.showDialog(jLabel1, "Select patient segments directory");
            if (niFolderRetVal == JFileChooser.CANCEL_OPTION) {
                return;
            }
            File niFolder = niFolderChooser.getSelectedFile();
            if (niFolder.isDirectory()) {
                niFolderPath = niFolder.getAbsolutePath();
                returned = true;
            } else {
                JOptionPane.showMessageDialog(niFolderChooser, "You selected a file not a folder");
            }
        }
        returned = false;
        while (returned == false) {
            returned = dicomFileChooser();
        }
    }//GEN-LAST:event_allPatientBtnMouseClicked

    private void TIMaxSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TIMaxSliderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TIMaxSliderMouseClicked

    private void WATMinSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WATMinSliderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_WATMinSliderMouseClicked

    private void WATMaxSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WATMaxSliderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_WATMaxSliderMouseClicked

    private void TIMinSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TIMinSliderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TIMinSliderMouseClicked

    private void BATMaxSiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BATMaxSiderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BATMaxSiderMouseClicked

    private void BATMinSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BATMinSliderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BATMinSliderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }
    
   private Hashtable<String, String[]> pathlist_gen () {
       
       String subjectDir = jTextField1.getText();
       String studyDir = jTextField2.getText();
       String mriDir = jTextField3.getText();
       String segDir = jTextField4.getText();
       // Split up the mri folder options into individual option strings
       String[] mriOptions = mriDir.split(", ");
       String[] studyOptions = studyDir.split(", ");
       int pathListSize = 4;
       Hashtable<String, String[]> pathList = new Hashtable<String, String[]>();
       
       String[] subjectDirList = {subjectDir};
       pathList.put("subjectDir", subjectDirList);
       String[] segmentDirList = {segDir};
       pathList.put("segmentFile", segmentDirList);
       pathList.put("studyOptions", studyOptions);
       pathList.put("mriOptions", mriOptions);
       
       return pathList;
   }
   private void start() {
        //csvFilePath = "/home/ariane/Desktop/TestFiles/test2.csv";
        /// nigzFilePath = "/media/ariane/GRMCULXFRER_EN_DVD/MRI_RESEARCH/019-30052_BAT.nii.gz";//"/home/ariane/Desktop/TestFiles/Segmentation files_BAT/010-04020_BAT.nii.gz";
        //dicomFolderPath = "/media/ariane/GRMCULXFRER_EN_DVD/MRI_RESEARCH";//"/home/ariane/Desktop/TestFiles/MRI 4.5";
        CsvWriter csv = new CsvWriter(csvFilePath);
        ComputeCalc calc = new ComputeCalc();
        // Normally this would be gotten from the users input however for 
        // testing this is the default if they don't specify a list     
        //String[] pathlist = {"MRI_RESEARCH", "MRI_BRAIN", "AX", "SCAPULA", "FP", "FF", "RR"};\

        Hashtable<String, String[]> pathlist = pathlist_gen();
        //pathlist[0] = "GUSTO_RESEARCH";
        //pathlist[1] = "GUSTO_RESEARCH";        
        //String s = jTextField1.getText();
        ProcessFile proc = new ProcessFile(csv, calc, pathlist);
        ArrayList<ProcessFile> procList = new ArrayList<>();
        csv.writeFirstRow(bounds);
        int count = 0;
        ArrayList<Thread> threads = new ArrayList<>();
        if (singlePatient == true) {
            progressBar.setMinimum(count);
            progressBar.setMaximum(1);
            ProcessFile singleProc = new ProcessFile(csv, calc, pathlist);
            singleProc.setParams(nigzFilePath, dicomFolderPath, bounds);
            singleProc.run();
            progressBar.setValue(1);
        } else {
            File[] subfoldersFiles = proc.openDicom.getSubfoldersFiles(niFolderPath);
            int length = subfoldersFiles.length;
            progressBar.setMinimum(count);
            progressBar.setMaximum(length);
            for (File file: subfoldersFiles) {
                ProcessFile process = new ProcessFile(csv, calc, pathlist);
                procList.add(process);
                process.setParams(file.getAbsolutePath(), dicomFolderPath, bounds);
                process.start();
                count ++;
                progressBar.setValue(count);
            }
            for (ProcessFile process: procList) {
                try {
                    process.thread.join();
                } catch (InterruptedException ex) {
                    Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        csv.closeCSVWriter();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider BATMaxSider;
    private javax.swing.JSlider BATMinSlider;
    private javax.swing.JButton CSVPathBtn;
    private javax.swing.JSlider TIMaxSlider;
    private javax.swing.JSlider TIMinSlider;
    private javax.swing.JSlider WATMaxSlider;
    private javax.swing.JSlider WATMinSlider;
    private javax.swing.JButton allPatientBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton singlePatientBtn;
    private javax.swing.JButton startBtn;
    // End of variables declaration//GEN-END:variables
}
